// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8rfCvfvzhNHFNinB762SHD0GRoY5Dz3w',
    appId: '1:565297319963:web:df999b36a012eaf1b028be',
    messagingSenderId: '565297319963',
    projectId: 'cinematick-abd82',
    authDomain: 'cinematick-abd82.firebaseapp.com',
    storageBucket: 'cinematick-abd82.firebasestorage.app',
    measurementId: 'G-RRPDLRFD6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBreAEwJXrhI15TigjLTv8gmClE0unzwKI',
    appId: '1:565297319963:android:ba9fdd7fe721c43fb028be',
    messagingSenderId: '565297319963',
    projectId: 'cinematick-abd82',
    storageBucket: 'cinematick-abd82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMikIaPpW4U5LTFzLSBL3jbIGfvc4l3t8',
    appId: '1:565297319963:ios:ffd67215c17235a4b028be',
    messagingSenderId: '565297319963',
    projectId: 'cinematick-abd82',
    storageBucket: 'cinematick-abd82.firebasestorage.app',
    iosBundleId: 'com.cinematick.cinematick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMikIaPpW4U5LTFzLSBL3jbIGfvc4l3t8',
    appId: '1:565297319963:ios:ffd67215c17235a4b028be',
    messagingSenderId: '565297319963',
    projectId: 'cinematick-abd82',
    storageBucket: 'cinematick-abd82.firebasestorage.app',
    iosBundleId: 'com.cinematick.cinematick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8rfCvfvzhNHFNinB762SHD0GRoY5Dz3w',
    appId: '1:565297319963:web:cf634f1ab7772499b028be',
    messagingSenderId: '565297319963',
    projectId: 'cinematick-abd82',
    authDomain: 'cinematick-abd82.firebaseapp.com',
    storageBucket: 'cinematick-abd82.firebasestorage.app',
    measurementId: 'G-TDXLWF4H84',
  );
}
